In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('Task_Data.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        96 non-null     int64
 1   Team      96 non-null     object
 2   Country   96 non-null     object
 3   NameF     96 non-null     object
 4   NameL     96 non-null     object
 5   Weight    91 non-null     float64
 6   Height    96 non-null     object
 7   DOB       90 non-null     datetime64[ns]
 8   Hometown  96 non-null     object
 9   Prov      96 non-null     object
 10  Pos       96 non-null     object
 11  Age       96 non-null     int64
 12  HeightFt  96 non-null     float64
 13  HtIn      96 non-null     int64
 14  BMI       96 non-null     int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(8)
memory usage: 11.4+ KB

In [4]:
df.dropna(axis=0,subset=['Weight'],inplace=True)
df

,ID,Team,Country,NameF,NameL,Weight,Height,DOB,Hometown,Prov,Pos,Age,HeightFt,HtIn,BMI
0,1,Women,Canada,Meghan,Agosta,148.0,5'7,1987-02-12,Ruthven,Ont.,Forward,35,5.583333,67,23
1,2,Women,Canada,Rebecca,Johnston,148.0,5'9,1989-09-24,Sudbury,Ont.,Forward,32,5.750000,69,22
2,3,Women,Canada,Laura,Stacey,156.0,5'10,1994-05-05,Kleinburg,Ont.,Forward,28,5.833333,70,22
3,4,Women,Canada,Jennifer,Wakefield,172.0,5'10,1989-06-15,Pickering,Ont.,Forward,33,5.833333,70,25
4,5,Women,Canada,Jillian,Saulnier,144.0,5'5,1992-03-07,Halifax,N.S.,Forward,30,5.416667,65,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,Men,USA,Ryan,Stoa,210.0,6'3,1987-04-13,Bloomington,Minn.,Forward,35,6.250000,75,26
92,93,Men,USA,Troy,Terry,179.0,6'0,1997-09-10,Highlands Ranch,Colo.,Forward,24,6.000000,72,24
93,94,Men,USA,Noah,Welch,215.0,6'4,1982-08-26,Brighton,Mass.,Defence,39,6.333333,76,26
94,95,Men,USA,James,Wisniewski,205.0,6'0,1984-02-21,Canton,Mich.,Defence,38,6.000000,72,28
95,96,Men,USA,Ryan,Zapolski,203.0,6'0,1986-11-11,Erie,Pa.,Goalie,35,6.000000,72,28

In [5]:
df['DOB'].fillna(value='na',inplace=True)

In [6]:
df['Pos']

0     Forward
1     Forward
2     Forward
3     Forward
4     Forward
       ...
91    Forward
92    Forward
93    Defence
94    Defence
95     Goalie
Name: Pos, Length: 91, dtype: object

In [12]:
df1 = df.groupby('Pos')
df1.mean()

                ID      Weight        Age  HeightFt       HtIn        BMI
Pos
Defence  50.888889  174.037037  39.444444  5.817901  69.814815  24.925926
Forward  44.679245  172.660377  34.207547  5.779874  69.358491  25.094340
Goalie   54.363636  175.181818  40.454545  5.886364  70.636364  24.545455

In [8]:
df.groupby('Team').mean()['Weight']['Women']

151.38095238095238

In [9]:
df.groupby('Team').median()['HtIn']['Men']

72.0

In [21]:
df2 = df[df['Country']=='Canada'][df['Team']=='Men']

C:\Users\Prajjwal Kumar\AppData\Local\Temp\ipykernel_36704\3393964996.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[df['Country']=='Canada'][df['Team']=='Men']

In [22]:
df2

,ID,Team,Country,NameF,NameL,Weight,Height,DOB,Hometown,Prov,Pos,Age,HeightFt,HtIn,BMI
23,24,Men,Canada,Gilbert,BrulÃ©,190.0,5'11,1987-01-01 00:00:00,Vancouver,B.C.,Forward,35,5.916667,71,26
24,25,Men,Canada,Wojtek,Wolski,220.0,6'3,1986-02-24 00:00:00,Toronto,Ont.,Forward,36,6.250000,75,27
25,26,Men,Canada,Derek,Roy,187.0,5'9,1983-05-04 00:00:00,Rockland,Ont.,Forward,39,5.750000,69,28
26,27,Men,Canada,Chris,Kelly,194.0,6'0,1980-11-11 00:00:00,Toronto,Ont.,Forward,41,6.000000,72,26
27,28,Men,Canada,Rob,Klinkhammer,214.0,6'3,1986-08-12 00:00:00,Lethbridge,Alta.,Forward,35,6.250000,75,27
28,29,Men,Canada,Brandon,Kozun,170.0,5'8,1990-03-08 00:00:00,Calgary,Alta.,Forward,32,5.666667,68,26
29,30,Men,Canada,Quinton,Howden,190.0,6'2,1992-01-21 00:00:00,Oakbank,Man.,Forward,30,6.166667,74,24
30,31,Men,Canada,RenÃ©,Bourque,216.0,6'2,1981-12-10 00:00:00,Lac La Biche,Alta.,Forward,40,6.166667,74,28
31,32,Men,Canada,Andrew,Ebbett,176.0,5'9,1983-01-02 00:00:00,Vernon,B.C.,Forward,39,5.750000,69,26
32,33,Men,Canada,Mason,Raymond,179.0,6'1,1985-09-17 00:00:00,Cochrane,Alta.,Forward,36,6.083333,73,24
33,34,Men,Canada,Eric,Oâ€™Dell,201.0,6'1,1990-06-21 00:00:00,Ottawa,Ont.,Forward,32,6.083333,73,27
34,35,Men,Canada,Maxim,Lapierre,216.0,6'0,1985-03-29 00:00:00,Brossard,Que.,Forward,37,6.000000,72,29
35,36,Men,Canada,Linden,Vey,190.0,6'0,1991-07-17 00:00:00,Wakaw,Sask.,Forward,30,6.000000,72,26
36,37,Men,Canada,Christian,Thomas,174.0,5'9,1992-05-26 00:00:00,Toronto,Ont.,Forward,30,5.750000,69,26
37,38,Men,Canada,Karl,Stollery,181.0,5'11,1987-11-21 00:00:00,Camrose,Alta.,Defence,34,5.916667,71,25
38,39,Men,Canada,Chris,Lee,187.0,6'0,1980-10-03 00:00:00,MacTier,Ont.,Defence,41,6.000000,72,25
39,40,Men,Canada,Chay,Genoway,170.0,5'9,1986-12-20 00:00:00,Morden,Man.,Defence,35,5.750000,69,25
40,41,Men,Canada,Marc-Andre,Gragnani,205.0,6'3,1987-03-11 00:00:00,Lâ€™ÃŽle-Bizard,Que.,Defence,35,6.250000,75,26
41,42,Men,Canada,Stefan,Elliott,190.0,6'1,1991-01-30 00:00:00,Vancouver,B.C.,Defence,31,6.083333,73,25
42,43,Men,Canada,Cody,Goloubef,200.0,6'1,1989-11-30 00:00:00,Oakville,Ont.,Defence,32,6.083333,73,26
43,44,Men,Canada,Mat,Robinson,185.0,5'10,1986-06-20 00:00:00,Calgary,Alta.,Defence,36,5.833333,70,27
44,45,Men,Canada,Maxim,Noreau,198.0,6'0,1987-05-24 00:00:00,Montreal,Que.,Defence,35,6.000000,72,27
45,46,Men,Canada,Ben,Scrivens,181.0,6'2,1986-09-11 00:00:00,Spruce Grove,Alta.,Goalie,35,6.166667,74,23
46,47,Men,Canada,Kevin,Poulin,205.0,6'2,1990-04-12 00:00:00,Montreal,Que.,Goalie,32,6.166667,74,26
47,48,Men,Canada,Justin,Peters,210.0,6'1,na,Blyth,Ont.,Goalie,122,6.083333,73,28

In [25]:
df3 = df[df['Country']=='USA'][df['Team']=='Women']

C:\Users\Prajjwal Kumar\AppData\Local\Temp\ipykernel_36704\1912939659.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3 = df[df['Country']=='USA'][df['Team']=='Women']

In [26]:
df3

,ID,Team,Country,NameF,NameL,Weight,Height,DOB,Hometown,Prov,Pos,Age,HeightFt,HtIn,BMI
48,49,Women,USA,Cayla,Barnes,145.0,5'1,1999-01-07 00:00:00,Eastvale,Calif.,Defence,23,5.083333,61,27
49,50,Women,USA,Kacey,Bellamy,145.0,5'7,1987-04-22 00:00:00,Westfield,Mass.,Defence,35,5.583333,67,23
50,51,Women,USA,Hannah,Brandt,150.0,5'6,1993-11-27 00:00:00,Vadnais Heights,Minn.,Forward,28,5.500000,66,24
52,53,Women,USA,Kendall,Coyne,123.0,5'2,1992-05-25 00:00:00,Palos Heights,Ill.,Forward,30,5.166667,62,22
53,54,Women,USA,Brianna,Decker,150.0,5'4,1991-05-13 00:00:00,Dousman,Wis.,Forward,31,5.333333,64,26
55,56,Women,USA,Kali,Flanagan,142.0,5'4,1995-09-19 00:00:00,Burlington,Mass.,Defence,26,5.333333,64,24
56,57,Women,USA,Nicole,Hensley,155.0,5'7,1994-06-23 00:00:00,Lakewood,Colo.,Goalie,27,5.583333,67,24
57,58,Women,USA,Megan,Keller,160.0,5'11,1996-05-01 00:00:00,Farmington,Mich.,Defence,26,5.916667,71,22
58,59,Women,USA,Amanda,Kessel,136.0,5'5,na,Madison,Wis.,Forward,122,5.416667,65,23
59,60,Women,USA,Hilary,Knight,175.0,5'11,1989-07-12 00:00:00,Sun Valley,Idaho,Forward,32,5.916667,71,24
60,61,Women,USA,Jocelyne,Lamoureux-Davidson,150.0,5'6,1989-07-03 00:00:00,Grand Forks,N.D.,Forward,32,5.500000,66,24
61,62,Women,USA,Monique,Lamoureux-Morando,147.0,5'6,1989-07-03 00:00:00,Grand Forks,N.D.,Forward,32,5.500000,66,24
62,63,Women,USA,Gigi,Marvin,159.0,5'8,1987-03-07 00:00:00,Warroad,Minn.,Forward,35,5.666667,68,24
63,64,Women,USA,Sidney,Morin,140.0,5'5,na,Minnetonka,Minn.,Defence,122,5.416667,65,23
64,65,Women,USA,Kelly,Pannek,165.0,5'8,1995-12-29 00:00:00,Plymouth,Minn.,Forward,26,5.666667,68,25
65,66,Women,USA,Amanda,Pelkey,135.0,5'3,1993-05-29 00:00:00,Montpelier,Vt.,Forward,29,5.250000,63,24
67,68,Women,USA,Alex,Rigsby,150.0,5'7,1992-01-03 00:00:00,Delafield,Wis.,Goalie,30,5.583333,67,23
69,70,Women,USA,Haley,Skarupa,140.0,5'6,1994-01-03 00:00:00,Rockville,Md.,Forward,28,5.500000,66,23
70,71,Women,USA,Lee,Stecklein,175.0,6'0,na,Roseville,Minn.,Defence,122,6.000000,72,24

In [27]:
df4 = pd.concat([df2,df3])

In [28]:
df4

,ID,Team,Country,NameF,NameL,Weight,Height,DOB,Hometown,Prov,Pos,Age,HeightFt,HtIn,BMI
23,24,Men,Canada,Gilbert,BrulÃ©,190.0,5'11,1987-01-01 00:00:00,Vancouver,B.C.,Forward,35,5.916667,71,26
24,25,Men,Canada,Wojtek,Wolski,220.0,6'3,1986-02-24 00:00:00,Toronto,Ont.,Forward,36,6.250000,75,27
25,26,Men,Canada,Derek,Roy,187.0,5'9,1983-05-04 00:00:00,Rockland,Ont.,Forward,39,5.750000,69,28
26,27,Men,Canada,Chris,Kelly,194.0,6'0,1980-11-11 00:00:00,Toronto,Ont.,Forward,41,6.000000,72,26
27,28,Men,Canada,Rob,Klinkhammer,214.0,6'3,1986-08-12 00:00:00,Lethbridge,Alta.,Forward,35,6.250000,75,27
28,29,Men,Canada,Brandon,Kozun,170.0,5'8,1990-03-08 00:00:00,Calgary,Alta.,Forward,32,5.666667,68,26
29,30,Men,Canada,Quinton,Howden,190.0,6'2,1992-01-21 00:00:00,Oakbank,Man.,Forward,30,6.166667,74,24
30,31,Men,Canada,RenÃ©,Bourque,216.0,6'2,1981-12-10 00:00:00,Lac La Biche,Alta.,Forward,40,6.166667,74,28
31,32,Men,Canada,Andrew,Ebbett,176.0,5'9,1983-01-02 00:00:00,Vernon,B.C.,Forward,39,5.750000,69,26
32,33,Men,Canada,Mason,Raymond,179.0,6'1,1985-09-17 00:00:00,Cochrane,Alta.,Forward,36,6.083333,73,24
33,34,Men,Canada,Eric,Oâ€™Dell,201.0,6'1,1990-06-21 00:00:00,Ottawa,Ont.,Forward,32,6.083333,73,27
34,35,Men,Canada,Maxim,Lapierre,216.0,6'0,1985-03-29 00:00:00,Brossard,Que.,Forward,37,6.000000,72,29
35,36,Men,Canada,Linden,Vey,190.0,6'0,1991-07-17 00:00:00,Wakaw,Sask.,Forward,30,6.000000,72,26
36,37,Men,Canada,Christian,Thomas,174.0,5'9,1992-05-26 00:00:00,Toronto,Ont.,Forward,30,5.750000,69,26
37,38,Men,Canada,Karl,Stollery,181.0,5'11,1987-11-21 00:00:00,Camrose,Alta.,Defence,34,5.916667,71,25
38,39,Men,Canada,Chris,Lee,187.0,6'0,1980-10-03 00:00:00,MacTier,Ont.,Defence,41,6.000000,72,25
39,40,Men,Canada,Chay,Genoway,170.0,5'9,1986-12-20 00:00:00,Morden,Man.,Defence,35,5.750000,69,25
40,41,Men,Canada,Marc-Andre,Gragnani,205.0,6'3,1987-03-11 00:00:00,Lâ€™ÃŽle-Bizard,Que.,Defence,35,6.250000,75,26
41,42,Men,Canada,Stefan,Elliott,190.0,6'1,1991-01-30 00:00:00,Vancouver,B.C.,Defence,31,6.083333,73,25
42,43,Men,Canada,Cody,Goloubef,200.0,6'1,1989-11-30 00:00:00,Oakville,Ont.,Defence,32,6.083333,73,26
43,44,Men,Canada,Mat,Robinson,185.0,5'10,1986-06-20 00:00:00,Calgary,Alta.,Defence,36,5.833333,70,27
44,45,Men,Canada,Maxim,Noreau,198.0,6'0,1987-05-24 00:00:00,Montreal,Que.,Defence,35,6.000000,72,27
45,46,Men,Canada,Ben,Scrivens,181.0,6'2,1986-09-11 00:00:00,Spruce Grove,Alta.,Goalie,35,6.166667,74,23
46,47,Men,Canada,Kevin,Poulin,205.0,6'2,1990-04-12 00:00:00,Montreal,Que.,Goalie,32,6.166667,74,26
47,48,Men,Canada,Justin,Peters,210.0,6'1,na,Blyth,Ont.,Goalie,122,6.083333,73,28
48,49,Women,USA,Cayla,Barnes,145.0,5'1,1999-01-07 00:00:00,Eastvale,Calif.,Defence,23,5.083333,61,27
49,50,Women,USA,Kacey,Bellamy,145.0,5'7,1987-04-22 00:00:00,Westfield,Mass.,Defence,35,5.583333,67,23
50,51,Women,USA,Hannah,Brandt,150.0,5'6,1993-11-27 00:00:00,Vadnais Heights,Minn.,Forward,28,5.500000,66,24
52,53,Women,USA,Kendall,Coyne,123.0,5'2,1992-05-25 00:00:00,Palos Heights,Ill.,Forward,30,5.166667,62,22
53,54,Women,USA,Brianna,Decker,150.0,5'4,1991-05-13 00:00:00,Dousman,Wis.,Forward,31,5.333333,64,26
55,56,Women,USA,Kali,Flanagan,142.0,5'4,1995-09-19 00:00:00,Burlington,Mass.,Defence,26,5.333333,64,24
56,57,Women,USA,Nicole,Hensley,155.0,5'7,1994-06-23 00:00:00,Lakewood,Colo.,Goalie,27,5.583333,67,24
57,58,Women,USA,Megan,Keller,160.0,5'11,1996-05-01 00:00:00,Farmington,Mich.,Defence,26,5.916667,71,22
58,59,Women,USA,Amanda,Kessel,136.0,5'5,na,Madison,Wis.,Forward,122,5.416667,65,23
59,60,Women,USA,Hilary,Knight,175.0,5'11,1989-07-12 00:00:00,Sun Valley,Idaho,Forward,32,5.916667,71,24
60,61,Women,USA,Jocelyne,Lamoureux-Davidson,150.0,5'6,1989-07-03 00:00:00,Grand Forks,N.D.,Forward,32,5.500000,66,24
61,62,Women,USA,Monique,Lamoureux-Morando,147.0,5'6,1989-07-03 00:00:00,Grand Forks,N.D.,Forward,32,5.500000,66,24
62,63,Women,USA,Gigi,Marvin,159.0,5'8,1987-03-07 00:00:00,Warroad,Minn.,Forward,35,5.666667,68,24
63,64,Women,USA,Sidney,Morin,140.0,5'5,na,Minnetonka,Minn.,Defence,122,5.416667,65,23
64,65,Women,USA,Kelly,Pannek,165.0,5'8,1995-12-29 00:00:00,Plymouth,Minn.,Forward,26,5.666667,68,25
65,66,Women,USA,Amanda,Pelkey,135.0,5'3,1993-05-29 00:00:00,Montpelier,Vt.,Forward,29,5.250000,63,24
67,68,Women,USA,Alex,Rigsby,150.0,5'7,1992-01-03 00:00:00,Delafield,Wis.,Goalie,30,5.583333,67,23
69,70,Women,USA,Haley,Skarupa,140.0,5'6,1994-01-03 00:00:00,Rockville,Md.,Forward,28,5.500000,66,23
70,71,Women,USA,Lee,Stecklein,175.0,6'0,na,Roseville,Minn.,Defence,122,6.000000,72,24

In [32]:
pd.pivot_table(df,index=["Team","Age"],aggfunc=[np.mean,len])

                mean                                             len          \
                 BMI  HeightFt       HtIn         ID      Weight BMI Country
Team  Age
Men   24   24.000000  6.000000  72.000000  93.000000  179.000000   1       1
      25   26.500000  6.291667  75.500000  78.000000  215.000000   2       2
      26   26.000000  6.083333  73.000000  78.000000  196.000000   1       1
      30   25.333333  5.972222  71.666667  34.333333  184.666667   3       3
      31   25.500000  6.083333  73.000000  64.000000  193.000000   2       2
      32   26.250000  6.000000  72.000000  38.250000  194.000000   4       4
      33   26.000000  5.875000  70.500000  73.000000  182.500000   2       2
      34   25.200000  5.866667  70.400000  78.000000  178.600000   5       5
      35   26.000000  6.066667  72.800000  57.600000  195.500000  10      10
      36   26.000000  5.916667  71.000000  57.166667  186.500000   6       6
      37   26.666667  6.027778  72.333333  66.000000  200.333333   3       3
      38   28.000000  6.000000  72.000000  95.000000  205.000000   1       1
      39   26.750000  5.958333  71.500000  60.750000  194.500000   4       4
      40   28.000000  6.166667  74.000000  31.000000  216.000000   1       1
      41   25.500000  6.000000  72.000000  33.000000  190.500000   2       2
      43   27.000000  5.583333  67.000000  80.000000  175.000000   1       1
      122  28.000000  6.083333  73.000000  48.000000  210.000000   1       1
Women 23   27.000000  5.083333  61.000000  49.000000  145.000000   1       1
      26   22.750000  5.625000  67.500000  47.750000  149.250000   4       4
      27   22.666667  5.583333  67.000000  28.666667  146.333333   3       3
      28   23.400000  5.633333  67.600000  32.200000  152.200000   5       5
      29   26.500000  5.375000  64.500000  41.000000  157.500000   2       2
      30   23.750000  5.416667  65.000000  33.000000  144.000000   4       4
      31   24.500000  5.583333  67.000000  18.500000  155.500000   6       6
      32   23.800000  5.666667  68.000000  40.400000  157.400000   5       5
      33   23.000000  5.750000  69.000000  13.000000  154.000000   2       2
      34   24.500000  5.541667  66.500000  12.500000  154.500000   2       2
      35   23.000000  5.625000  67.500000  33.750000  149.500000   4       4
      37   21.000000  5.750000  69.000000  19.000000  139.000000   1       1
      122  23.333333  5.611111  67.333333  64.666667  150.333333   3       3


          DOB Height HeightFt Hometown HtIn  ID NameF NameL Pos Prov Weight
Team  Age
Men   24    1      1        1        1    1   1     1     1   1    1      1
      25    2      2        2        2    2   2     2     2   2    2      2
      26    1      1        1        1    1   1     1     1   1    1      1
      30    3      3        3        3    3   3     3     3   3    3      3
      31    2      2        2        2    2   2     2     2   2    2      2
      32    4      4        4        4    4   4     4     4   4    4      4
      33    2      2        2        2    2   2     2     2   2    2      2
      34    5      5        5        5    5   5     5     5   5    5      5
      35   10     10       10       10   10  10    10    10  10   10     10
      36    6      6        6        6    6   6     6     6   6    6      6
      37    3      3        3        3    3   3     3     3   3    3      3
      38    1      1        1        1    1   1     1     1   1    1      1
      39    4      4        4        4    4   4     4     4   4    4      4
      40    1      1        1        1    1   1     1     1   1    1      1
      41    2      2        2        2    2   2     2     2   2    2      2
      43    1      1        1        1    1   1     1     1   1    1      1
      122   1      1        1        1    1   1     1     1   1    1      1
Women 23    1      1        1        1    1   1     1     1   1    1      1
      26    4      4        4        4    4   4     4     4   4    4      4
      27    3      3        3        3    3   3     3     3   3    3      3
      28    5      5        5        5    5   5     5     5   5    5      5
      29    2      2        2        2    2   2     2     2   2    2      2
      30    4      4        4        4    4   4     4     4   4    4      4
      31    6      6        6        6    6   6     6     6   6    6      6
      32    5      5        5        5    5   5     5     5   5    5      5
      33    2      2        2        2    2   2     2     2   2    2      2
      34    2      2        2        2    2   2     2     2   2    2      2
      35    4      4        4        4    4   4     4     4   4    4      4
      37    1      1        1        1    1   1     1     1   1    1      1
      122   3      3        3        3    3   3     3     3   3    3      3